# -*- coding: utf-8 -*-
"""Bag of Words

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rGxgTaitWe8b5o7Z3LJQBoy4XdF3Kv7q
"""

# import libraries
from sklearn.feature_extraction.text import CountVectorizer

# create a sample doc
d1 = ["I have a dream that my four little children will I have a dream that one day on the red hills of Georgia I have a dream today!"]

# create BoW model
vectorize  = CountVectorizer()
X = vectorize.fit_transform(d1)

print("Features (Vocabulary):", vectorize.get_feature_names_out())

print("BoW Matrix:\n", X.toarray())





