# -*- coding: utf-8 -*-
"""3.1_TF-IDF-based_extractive_summarizer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zlxTcERpHT9RlvL0uAEhilLU8d88H8A-
"""

import nltk
import re
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
nltk.download('punkt')
nltk.download('punkt_tab')
from nltk.tokenize import sent_tokenize

text = """Winter is coming" is a well-known phrase, particularly associated with the Game of Thrones series, and it carries multiple meanings.
Literally, it refers to the changing of seasons and the approach of colder, harsher weather. Figuratively, it serves as a warning of impending hardship, challenges, and difficult times.
In the context of Game of Thrones, it's the motto of House Stark, and it signifies a reminder to be prepared for danger, scarcity, and struggle, as winter in that world is a long and perilous season."""

sent = sent_tokenize(text)

def clean_txt(sentence):
  sentence = re.sub(r'\W', ' ', sentence)
  sentence = re.sub(r'\s+', ' ', sentence)
  return sentence.strip().lower()

cleaned = [clean_txt(s) for s in sent]

vectorizer = TfidfVectorizer()
matrix = vectorizer.fit_transform(cleaned)

similarity_matrix = cosine_similarity(matrix)

# Summing similarity scores for each sentence
sentence_scores = similarity_matrix.sum(axis=1)

# Number of sentences to extract
num_sentences = 3

# Get top-ranked sentence indices
top_sentence_indices = sentence_scores.argsort()[-num_sentences:][::-1]

# Sort them in original order (to maintain readability)
top_sentence_indices.sort()

# Extract final summary
summary = " ".join([sent[i] for i in top_sentence_indices])
print(summary)

