# -*- coding: utf-8 -*-
"""Named Entity Recognition (NER)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vLTZDK58xlzRs3vNuLKJm7ffXgrku6gL
"""

import spacy

# Load English language model
nlp = spacy.load("en_core_web_sm")

text = "Elon Musk founded SpaceX in California in 2002."

# Process text
doc = nlp(text)

# Extract entities
for ent in doc.ents:
    print(ent.text, "→", ent.label_)

from spacy import displacy
displacy.render(doc, style="ent", jupyter=True)

"""________________________________________________________________________________________________________________________________________________________________"""

""" Lets practice """

sent = "Mark Zuckerberg launched Facebook from his Harvard dorm room in 2004."

doc = nlp(sent)

for ent in doc.ents:
  print(ent.text, "-> ", ent.label_)





