# -*- coding: utf-8 -*-
"""POS Tagging (Parts of Speech)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u_HhibX8fTv6TA5he4Bp8Ali1F58-TSS
"""

'''Sentence: "The quick brown fox jumps over the lazy dog."
Tagged: [('The', 'DT'), ('quick', 'JJ'), ('brown', 'JJ'), ('fox', 'NN'), ...]'''

nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')

import nltk
from nltk import word_tokenize, pos_tag

text = "You become what do you think about most of the time."

tokens = word_tokenize(text)
tagged = pos_tag(tokens)

print(tagged)





